#
# Module manifest for module 'Set-DnsClientDohServer'
#
# Generated by: RocketToast
#
# Generated on: 3/20/2026
#

@{

# Script module or binary module file associated with this manifest.
RootModule = '.\Set-DnsClientDohServer.psm1'

# Version number of this module.
ModuleVersion = '0.0.1'

# Supported PSEditions
CompatiblePSEditions = @(5.1)

# ID used to uniquely identify this module
GUID = '6bb80105-7b5d-4cc6-9e5b-e226aba15b3b'

# Author of this module
Author = 'RocketToast'

# Copyright statement for this module
Copyright = '(c) RocketToast All rights reserved.'

# Description of the functionality provided by this module
Description = 'A module to set the DoH servers on your computer.'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Minimum version of the PowerShell host required by this module
PowerShellHostVersion = '5.1'

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = 'Set-DnsClientDohServer'

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'DNS', 'DoH', 'DNS Over HTTPS'

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/RocketToast/Set-DnsClientDohServer/blob/main/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/RocketToast/Set-DnsClientDohServer'

    } # End of PSData hashtable

} # End of PrivateData hashtable

}
